//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.23 at 10:08:23 PM IST 
//


package com.sage.FoodTrucks.pojo;

import java.math.BigDecimal;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.springframework.stereotype.Component;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="row">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="objectid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="applicant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="facilitytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cnn" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="locationdescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="blocklot" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                             &lt;element name="lot" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="permit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fooditems" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="schedule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="priorpermit" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="expirationdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="location">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="human_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                     &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Component
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "row"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected Response.Rows row;

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Row }
     *     
     */
    public Response.Rows getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Row }
     *     
     */
    public void setRow(Response.Rows value) {
        this.row = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="objectid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="applicant" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="facilitytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cnn" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="locationdescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="blocklot" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                   &lt;element name="lot" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="permit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fooditems" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="schedule" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="priorpermit" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="expirationdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="location">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="human_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                           &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class Rows {

        @XmlElement(required = true)
        protected List<Response.Rows.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Row.Row }
         *     
         */
        public List<Response.Rows.Row> getRow() {
            return row;
        }

        /**
         * Sets the value of the row property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Row.Row }
         *     
         */
        public void setRow(List<Response.Rows.Row> value) {
            this.row = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="objectid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="applicant" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="facilitytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cnn" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="locationdescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="blocklot" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *         &lt;element name="lot" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="permit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fooditems" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="schedule" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="priorpermit" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="expirationdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="location">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="human_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *                 &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "objectid",
            "applicant",
            "facilitytype",
            "cnn",
            "locationdescription",
            "address",
            "blocklot",
            "block",
            "lot",
            "permit",
            "status",
            "fooditems",
            "x",
            "y",
            "latitude",
            "longitude",
            "schedule",
            "received",
            "priorpermit",
            "expirationdate",
            "location"
        })
        public static class Row {

            @XmlSchemaType(name = "unsignedInt")
            protected long objectid;
            @XmlElement(required = true)
            protected String applicant;
            @XmlElement(required = true)
            protected String facilitytype;
            @XmlSchemaType(name = "unsignedInt")
            protected long cnn;
            @XmlElement(required = true)
            protected String locationdescription;
            @XmlElement(required = true)
            protected String address;
            @XmlSchemaType(name = "unsignedInt")
            protected long blocklot;
            @XmlSchemaType(name = "unsignedShort")
            protected int block;
            @XmlSchemaType(name = "unsignedByte")
            protected short lot;
            @XmlElement(required = true)
            protected String permit;
            @XmlElement(required = true)
            protected String status;
            @XmlElement(required = true)
            protected String fooditems;
            @XmlElement(required = true)
            protected BigDecimal x;
            @XmlElement(required = true)
            protected BigDecimal y;
            @XmlElement(required = true)
            protected BigDecimal latitude;
            @XmlElement(required = true)
            protected BigDecimal longitude;
            @XmlElement(required = true)
            protected String schedule;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar received;
            @XmlSchemaType(name = "unsignedByte")
            protected short priorpermit;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar expirationdate;
            @XmlElement(required = true)
            protected Response.Rows.Row.Location location;

            /**
             * Gets the value of the objectid property.
             * 
             */
            public long getObjectid() {
                return objectid;
            }

            /**
             * Sets the value of the objectid property.
             * 
             */
            public void setObjectid(long value) {
                this.objectid = value;
            }

            /**
             * Gets the value of the applicant property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplicant() {
                return applicant;
            }

            /**
             * Sets the value of the applicant property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplicant(String value) {
                this.applicant = value;
            }

            /**
             * Gets the value of the facilitytype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFacilitytype() {
                return facilitytype;
            }

            /**
             * Sets the value of the facilitytype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFacilitytype(String value) {
                this.facilitytype = value;
            }

            /**
             * Gets the value of the cnn property.
             * 
             */
            public long getCnn() {
                return cnn;
            }

            /**
             * Sets the value of the cnn property.
             * 
             */
            public void setCnn(long value) {
                this.cnn = value;
            }

            /**
             * Gets the value of the locationdescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocationdescription() {
                return locationdescription;
            }

            /**
             * Sets the value of the locationdescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocationdescription(String value) {
                this.locationdescription = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress(String value) {
                this.address = value;
            }

            /**
             * Gets the value of the blocklot property.
             * 
             */
            public long getBlocklot() {
                return blocklot;
            }

            /**
             * Sets the value of the blocklot property.
             * 
             */
            public void setBlocklot(long value) {
                this.blocklot = value;
            }

            /**
             * Gets the value of the block property.
             * 
             */
            public int getBlock() {
                return block;
            }

            /**
             * Sets the value of the block property.
             * 
             */
            public void setBlock(int value) {
                this.block = value;
            }

            /**
             * Gets the value of the lot property.
             * 
             */
            public short getLot() {
                return lot;
            }

            /**
             * Sets the value of the lot property.
             * 
             */
            public void setLot(short value) {
                this.lot = value;
            }

            /**
             * Gets the value of the permit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPermit() {
                return permit;
            }

            /**
             * Sets the value of the permit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPermit(String value) {
                this.permit = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the fooditems property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFooditems() {
                return fooditems;
            }

            /**
             * Sets the value of the fooditems property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFooditems(String value) {
                this.fooditems = value;
            }

            /**
             * Gets the value of the x property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setX(BigDecimal value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setY(BigDecimal value) {
                this.y = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLatitude(BigDecimal value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLongitude(BigDecimal value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the schedule property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSchedule() {
                return schedule;
            }

            /**
             * Sets the value of the schedule property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSchedule(String value) {
                this.schedule = value;
            }

            /**
             * Gets the value of the received property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getReceived() {
                return received;
            }

            /**
             * Sets the value of the received property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setReceived(XMLGregorianCalendar value) {
                this.received = value;
            }

            /**
             * Gets the value of the priorpermit property.
             * 
             */
            public short getPriorpermit() {
                return priorpermit;
            }

            /**
             * Sets the value of the priorpermit property.
             * 
             */
            public void setPriorpermit(short value) {
                this.priorpermit = value;
            }

            /**
             * Gets the value of the expirationdate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getExpirationdate() {
                return expirationdate;
            }

            /**
             * Sets the value of the expirationdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setExpirationdate(XMLGregorianCalendar value) {
                this.expirationdate = value;
            }

            /**
             * Gets the value of the location property.
             * 
             * @return
             *     possible object is
             *     {@link Response.Row.Row.Location }
             *     
             */
            public Response.Rows.Row.Location getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.Row.Row.Location }
             *     
             */
            public void setLocation(Response.Rows.Row.Location value) {
                this.location = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="human_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *       &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Location {

                @XmlAttribute(name = "human_address", required = true)
                protected String humanAddress;
                @XmlAttribute(name = "latitude", required = true)
                protected BigDecimal latitude;
                @XmlAttribute(name = "longitude", required = true)
                protected BigDecimal longitude;

                /**
                 * Gets the value of the humanAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHumanAddress() {
                    return humanAddress;
                }

                /**
                 * Sets the value of the humanAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHumanAddress(String value) {
                    this.humanAddress = value;
                }

                /**
                 * Gets the value of the latitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getLatitude() {
                    return latitude;
                }

                /**
                 * Sets the value of the latitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setLatitude(BigDecimal value) {
                    this.latitude = value;
                }

                /**
                 * Gets the value of the longitude property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getLongitude() {
                    return longitude;
                }

                /**
                 * Sets the value of the longitude property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setLongitude(BigDecimal value) {
                    this.longitude = value;
                }

            }

        }

    }

}
